### ISSUE TITLE
Gerber File?

### ISSUE THREAD

**Issue by andreacampanella** [putyn/nixie-clock#1]
Would be nice to have gerber files for the PCBs as well :)

**Comment by fabicodes** [comment]
[in4_control_v1.0_revA_2019-05-06.zip](https://github.com/putyn/nixie-clock/files/3177637/in4_control_v1.0_revA_2019-05-06.zip)
[in4_single_v0.2_revB_2019-05-06.zip](https://github.com/putyn/nixie-clock/files/3177638/in4_single_v0.2_revB_2019-05-06.zip)
[in4_single_v0.2_revA_2019-05-14.zip](https://github.com/putyn/nixie-clock/files/3177644/in4_single_v0.2_revA_2019-05-14.zip)
[boosst_new_2019-05-14.zip](https://github.com/putyn/nixie-clock/files/3177650/boosst_new_2019-05-14.zip)
[boosst_revA_2019-05-14.zip](https://github.com/putyn/nixie-clock/files/3177651/boosst_revA_2019-05-14.zip)
[boosst_revB_2019-05-14.zip](https://github.com/putyn/nixie-clock/files/3177652/boosst_revB_2019-05-14.zip)
